from . import customer_statement_unmail
from . import partner
from . import invoice
from . import product_template
from . import sale
from . import company
from . import account_follow_up_report
from . import payment_terms
from . import stock_quant
from . import pos_order
from . import purchase_order